### ISSUE TITLE
AttributeError: module 'modules.sd_samplers' has no attribute 'CFGDenoiser'

### ISSUE THREAD

**Issue by NoCrypt** [mcmonkeyprojects/sd-dynamic-thresholding#2]
![image](https://user-images.githubusercontent.com/57245077/215472550-b4224193-9206-48cd-bffc-1dc70aa51bef.png)

```bash
Error loading script: dynamic_thresholding.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py", line 91, in <module>
    class CustomCFGDenoiser(sd_samplers.CFGDenoiser):
AttributeError: module 'modules.sd_samplers' has no attribute 'CFGDenoiser'
```

More info:
- Using Colab
- Webui Hash: aa4688eb8345de583070ca9ddb4c6f585f06762b (latest as I'm writing this issue)

**Comment by mcmonkey4eva** [comment]
yep, WebUI updated to reorganize sampler code

**Comment by mcmonkey4eva** [comment]
Updated, works on the latest WebUI again!
