### ISSUE TITLE
AttributeError: 'DynThresh' object has no attribute 'step'

### ISSUE THREAD

**Issue by Badenstein** [mcmonkeyprojects/sd-dynamic-thresholding#21]
**I just installed the extension, updated and relaunched the webui. I received this error each time I tried to enable Dynamic Thresholding:**
Error completing request
Arguments: ('task(rsa3qrt092fsaik)', 'picture of a cat eating a pizza, yellow eyes, bushy tail, stripes, grey and white, pepperoni on the pizza', 'easynegative', [], 88, 15, False, False, 1, 1, 20, -1.0, -1.0, 0, 0, 0, False, 768, 512, True, 0.6, 2, 'Lanczos', 30, 0, 0, [], 0, False, '', 0, True, 8, 99, 'Half Cosine Up', 4, 'Half Cosine Up', 3.5, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 3, 0, False, False, 0, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, None, 50) {}
Traceback (most recent call last):
  File "K:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "K:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "K:\stable-diffusion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "K:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "K:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "K:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 836, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "K:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "K:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "K:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "K:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "K:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "K:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "K:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 153, in forward
    denoised = self.combine_denoised(x_out, conds_list, uncond, cond_scale)
  File "K:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 259, in combine_denoised
    return self.main_class.dynthresh(x_out[:-uncond.shape[0]], denoised_uncond, cond_scale, weights)
  File "K:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 164, in dynthresh
    mimicScale = self.interpretScale(self.mimic_scale, self.mimic_mode, self.mimic_scale_min)
  File "K:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 153, in interpretScale
    scale *= 1.0 - math.cos((self.step / max))
AttributeError: 'DynThresh' object has no attribute 'step'

**Comment by mcmonkey4eva** [comment]
Sorry about that! There was a bug introduced accidentally that was left in the live build for just under an hour - it's already patched, so just update and you'll be good.

**Comment by Badenstein** [comment]
Awesome. Thanks for the quick response.
