### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DavidSnow1** [mcmonkeyprojects/sd-dynamic-thresholding#22]
Hi there. I've just installed your extension using both methods of installation. Available and from URL (https://github.com/mcmonkeyprojects/sd-dynamic-thresholding). In both cases, I get the same error. Since I have the coding ability of an inebriated chimpanzee, I thought I'd ask for help here. Any clue as to what my issue is? Thank you for your time and effort. 

```
Error loading script: dynamic_thresholding.py
Traceback (most recent call last):
  File "C:\Users\Snow\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Snow\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Snow\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 15, in <module>
    import dynthres_unipc, dynthres_core
  File "C:\Users\Snow\stable-diffusion-webui\extensions\sd-dynamic-thresholding\dynthres_unipc.py", line 6, in <module>
    from modules.models.diffusion import uni_pc
ImportError: cannot import name 'uni_pc' from 'modules.models.diffusion' (unknown location)
```

**Comment by Lamaluo** [comment]
Got the same problem

**Comment by mcmonkey4eva** [comment]
Update your WebUI, UniPC was added to the WebUI last week, and I updated DynThresh to support it this morning.
(Alternately you can downdate the extension if you don't want to update the WebUI)
