### ISSUE TITLE
'CustomUniPCSampler' object has no attribute 'make_schedule' when using hi-res fix

### ISSUE THREAD

**Issue by Panchvzluck** [mcmonkeyprojects/sd-dynamic-thresholding#27]
Hi there, really nice extension! Was wondering if this issue is known.

When trying to use UniPC Sampler with dynamic-thresholding and hi-res fix, it gives the following issue when it should start applyng the hi-res fix.

```
Traceback (most recent call last):
  File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\Stable difussion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 908, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "G:\Stable difussion\stable-diffusion-webui\modules\sd_samplers_compvis.py", line 179, in sample_img2img
    self.sampler.make_schedule(ddim_num_steps=steps, ddim_eta=self.eta, ddim_discretize=p.ddim_discretize, verbose=False)
AttributeError: 'CustomUniPCSampler' object has no attribute 'make_schedule'
```

I've tested with R-ESRGAN 4X+ and others upscalers, but all seem to suffer the same issue.

Thanks!

**Comment by judgeou** [comment]
me to
