### ISSUE TITLE
Throws RuntimeError: quantile() input tensor must be either float or double dtype when using UniPC Sampler

### ISSUE THREAD

**Issue by diffusersd** [mcmonkeyprojects/sd-dynamic-thresholding#28]
I'm using webui-directml variation of webui since I'm using rx 6000 gpu on Windows. I didn't notice this issue in other samplers.
```
Traceback (most recent call last):
  File "X:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "X:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "X:\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "X:\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "X:\stable-diffusion-webui-directml\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "X:\stable-diffusion-webui-directml\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "X:\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 218, in sample
    samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
  File "X:\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 51, in launch_sampling
    return func()
  File "X:\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 218, in <lambda>
    samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
  File "X:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "X:\stable-diffusion-webui-directml\extensions\sd-dynamic-thresholding\dynthres_unipc.py", line 56, in sample
    x = uni_pc_inst.sample(img, steps=S, skip_type=shared.opts.uni_pc_skip_type, method="multistep", order=shared.opts.uni_pc_order, lower_order_final=shared.opts.uni_pc_lower_order_final)
  File "X:\stable-diffusion-webui-directml\modules\models\diffusion\uni_pc\uni_pc.py", line 758, in sample
    model_prev_list = [self.model_fn(x, vec_t)]
  File "X:\stable-diffusion-webui-directml\modules\models\diffusion\uni_pc\uni_pc.py", line 453, in model_fn
    return self.data_prediction_fn(x, t)
  File "X:\stable-diffusion-webui-directml\modules\models\diffusion\uni_pc\uni_pc.py", line 437, in data_prediction_fn
    noise = self.noise_prediction_fn(x, t)
  File "X:\stable-diffusion-webui-directml\modules\models\diffusion\uni_pc\uni_pc.py", line 431, in noise_prediction_fn
    return self.model(x, t)
  File "X:\stable-diffusion-webui-directml\modules\models\diffusion\uni_pc\uni_pc.py", line 417, in model
    res = self.model_fn_(x, t, cond, uncond)
  File "X:\stable-diffusion-webui-directml\extensions\sd-dynamic-thresholding\dynthres_unipc.py", line 107, in model_fn
    return dtData.dynthresh(noise, noise_uncond, guidance_scale, None)
  File "X:\stable-diffusion-webui-directml\extensions\sd-dynamic-thresholding\dynthres_core.py", line 70, in dynthresh
    cfg_max = torch.quantile(cfg_centered.abs(), self.threshold_percentile, dim=2).unsqueeze(2).double()
RuntimeError: quantile() input tensor must be either float or double dtype
```

**Comment by mcmonkey4eva** [comment]
I'm... surprised any of DynThresh works on the directml fork tbh, considering how closely some of the internal code is tied to the implementation details.

I don't know that I can really fix that. It's possible if you report it to the DirectML team they can do something?
I don't really have any idea how the DirectML fork works.
