### ISSUE TITLE
After 13/may update, error while running with multidiffusion upscaler on img2img

### ISSUE THREAD

**Issue by rehvka** [mcmonkeyprojects/sd-dynamic-thresholding#39]
Hello, one of the best extension out there. 
Id normally run multidifussion alongside dynamic thresholding but after todays update I get this message. Any idea how to fix it?

Error running process_batch: F:\AI\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
Traceback (most recent call last):
  File "F:\AI\stable-diffusion-webui\modules\scripts.py", line 436, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "F:\AI\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 127, in process_batch
    p.sampler = sd_samplers.create_sampler(fixed_sampler_name, p.sd_model)
  File "F:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 364, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "F:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 434, in create_sampler_hijack
    sampler = sd_samplers.create_sampler_original_md(name, model)
AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'

**Comment by mcmonkey4eva** [comment]
This looks like an issue with `multidiffusion-upscaler-for-automatic1111` rather than with dynthresh.
