### ISSUE TITLE
Error: unsupported operand type(s) for -=: 'bool' and 'str' 

### ISSUE THREAD

**Issue by DuckersMcQuack** [mcmonkeyprojects/sd-dynamic-thresholding#41]
Traceback (most recent call last):
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\img2img.py", line 182, in img2img
    processed = process_images(p)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\processing.py", line 1135, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 350, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 350, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 179, in forward
    denoised = self.combine_denoised(x_out, conds_list, uncond, cond_scale)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 170, in combine_denoised
    return self.main_class.dynthresh(x_out[:-uncond.shape[0]], denoised_uncond, cond_scale, weights)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\extensions\sd-dynamic-thresholding\dynthres_core.py", line 42, in dynthresh
    mimicScale = self.interpretScale(self.mimic_scale, self.mimic_mode, self.mimic_scale_min)
  File "H:\Stablediff\Automatic1111\stable-diffusion-webui\extensions\sd-dynamic-thresholding\dynthres_core.py", line 18, in interpretScale
    scale -= min
TypeError: unsupported operand type(s) for -=: 'bool' and 'str'

**Comment by mcmonkey4eva** [comment]
That... doesn't make sense, how did you get to that error? That seems to be claiming `mimic_scale` has turned into a boolean and `mimic_scale_min` has turned into a string??
