### ISSUE TITLE
pytorch 2.0.0 issue?

### ISSUE THREAD

**Issue by leittt** [mcmonkeyprojects/sd-dynamic-thresholding#52]
Error running process: G:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "G:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 400, in process
    # is only available in AUTOMATIC1111 1.3.0+, but might not be in forks.
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'hr_prompt'

**Comment by mcmonkey4eva** [comment]
Wrong repo lol. This is dynamic thresholding, that error is dynamic prompting.
