### ISSUE TITLE
Extension not showing up, Error message

### ISSUE THREAD

**Issue by artreloaded** [mcmonkeyprojects/sd-dynamic-thresholding#6]
I cant activate it in the UI because it doesnt appear. I get the following error message in the console

Error loading script: dynamic_thresholding.py
Traceback (most recent call last):
  File "C:\sd\stable-diffusion-webui-master\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\sd\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd\stable-diffusion-webui-master\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 17, in <module>
    from modules import scripts, sd_samplers, sd_samplers_kdiffusion, sd_samplers_common
ImportError: cannot import name 'sd_samplers_kdiffusion' from 'modules' (unknown location)

**Comment by mcmonkey4eva** [comment]
That looks like you updated the extension but didn't update the WebUI
