### ISSUE TITLE
Unable to update sd-dynamic-thresholding

### ISSUE THREAD

**Issue by Azura-13** [mcmonkeyprojects/sd-dynamic-thresholding#67]
Hi there (again sorry)

I'm unable to update the extension, in automatic extensions list, sd-dynamic-thresholding has no URL, branch, version, date infomation and update says unknown, auto update does not touch it. Tried putting the URL to reinstall it but it just said it was already installed and i have no idea how to uninstall it beyond deleting some file out of my folder.

Sorry and thanks again

*** Error completing request
*** Arguments: ('', 'https://github.com/mcmonkeyprojects/sd-dynamic-thresholding', '') {}
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 355, in install_extension_from_url
        assert not os.path.exists(target_dir), f'Extension directory already exists: {target_dir}'
    AssertionError: Extension directory already exists: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-thresholding

**Comment by Azura-13** [comment]
Sorry, found it's file, deleted it and reinstalled, this time I have branch info, So that should auto update now, Again thx for the help and the CFG fix
