### ISSUE TITLE
Support for the DDIM sampler?

### ISSUE THREAD

**Issue by giteeeeee** [mcmonkeyprojects/sd-dynamic-thresholding#7]
Error running process_batch: E:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 59, in process_batch
    raise RuntimeError(f"Cannot use sampler {p.sampler_name} with Dynamic Thresholding")
RuntimeError: Cannot use sampler DDIM with Dynamic Thresholding

It doesn't seem to like DDIM. Is it slightly possible to add support for DDIM?

Your extension works wonders btw. I've always been haunted by contrast issues with high cfg. I even trained a negative embedding just to counter the problem but without success. You literally saved my eyes thank you!

**Comment by mcmonkey4eva** [comment]
DDIM and PLMS weren't included initially as they use different code from all the other samplers. They're possible to support, but will require a completely different method of injecting DynThresh.

**Comment by giteeeeee** [comment]
> DDIM and PLMS weren't included initially as they use different code from all the other samplers. They're possible to support, but will require a completely different method of injecting DynThresh.

Understood. It's just ddim has been the fastest and better with detail + contrast for me. It'd be extra nice if you can make it happen. That said I'm really happy with the current feature already.
